### ISSUE TITLE
The Addon Is Not Working in Linux ( Ubontu 22.10 )

### ISSUE THREAD

**Issue by Subankar981** [gents83/NRG#11] opened 2023-11-23 14:50 UTC
![INOX](https://github.com/gents83/INOX/assets/140243616/d4aabe06-38c5-404c-a2c4-1f6610b952ef)

**Comment by gents83** [comment] 2024-01-28 17:14
Thanks for opening this issue - I still have to work on linux version of it

**Comment by gents83** [comment] 2024-01-28 17:14
Duplicate of #10

**Closed as completed by gents83** 2024-01-28 17:14 UTC
